name: Python Action

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace 'x' with the desired Python version

      - name: Install Dependencies  # Add this step if your script has dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with the actual requirements file if needed

      - name: Run Python Script
        run: python fill-form.py  # Replace 'your_script.py' with your actual script name
