name: Python Action

on:
  push:
    branches:
      - main

runs: 
  using: composite
 
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Replace 'x' with the desired Python version

    - name: Install Dependencies  # Add this step if your script has 
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with the actual requirements file if needed

    - name: Run Python Script
      shell: bash
      run: python fill-form.py  # Replace 'your_script.py' with your actual script name
