name: Workflow using External Action

on:
  push:
    branches:
      - main

jobs:
  use-external-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use External Action
        uses: mairazarate91/ethansbreakfast@v1

